input_string=input("enter a string:")
char_tuple=tuple(input_string)
print("String:",input_string)
print("Tuple of characters:",char_tuple)
tuple1=(1,"apple",3.14)
tuple2=(2,"banana",5,6.78)
tuple3=(7.89,8,"cherry")
merged_tuple=tuple1+tuple2+tuple3
print("Tuple1:",tuple1)
print("Tuple2:",tuple2)
print("Tuple3:",tuple3)
print("Merged Tuple:",merged_tuple)